export const CREATE_AGENT_REQUEST = 'CREATE_AGENT_REQUEST';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_FAIL = 'CREATE_AGENT_FAIL';

export const GET_AGENT_REQUEST='GET_AGENT_REQUEST';
export const GET_AGENT_SUCCESS='GET_AGENT_SUCCESS';
export const GET_AGENT_FAIL='GET_AGENT_FAIL';
